name: Hello world action

on:
  push:
    branches: [ "main", "develop", "feature/*" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Create Docker Network
        run: docker network create se-methods

      - name: Run MongoDB Container
        run: docker run -d --name mongo-dbserver --network se-methods mongo:latest

      - name: Build Docker Image
        run: docker build -t se_methods .

      - name: Run Application Container
        run: docker run --network se-methods --name devopscontainer se_methods

      - name: View Container Logs
        run: docker logs devopscontainer